### Lambda Functions

In [1]:
# python function definition
def add(x):
    return x+1
# changing it to lambda function
addOne = lambda x : x+1
print(add(10), addOne(10))
# Lambda function takes input first and last names, returns full_name
combineNames = lambda first, last : first + " " + last
print(combineNames("Islam", "Mahmoud"))

11 11
Islam Mahmoud


### NumPy

In [2]:
import numpy as np
np.__version__

'1.19.5'

In [3]:
## Defining a list & np array of known elements
listX = [1,2,3]
numpyArr = np.array(listX)
print(listX,numpyArr)
list2D = [[1,2,3],[4,5,6]]
numpy2D = np.array(list2D)
## Ndim returns the number of dimensions an a numpy array
print(list2D,'\n', numpy2D, numpy2D.ndim)

[1, 2, 3] [1 2 3]
[[1, 2, 3], [4, 5, 6]] 
 [[1 2 3]
 [4 5 6]] 2


In [4]:
## Creating a list/numpy arr from min to max with steps
listOfElements = list(range(1,9))
numpyArrOfElements = np.arange(start=1,stop=9, step=1)
print(listOfElements, numpyArrOfElements)
print(type(listOfElements), type(numpyArrOfElements))

[1, 2, 3, 4, 5, 6, 7, 8] [1 2 3 4 5 6 7 8]
<class 'list'> <class 'numpy.ndarray'>


In [5]:
## Creating an array of minimum n=3 dimensions
arr3D = np.array(listOfElements, ndmin=3)
print(arr3D)
## If the elements must fit in a n*2*2 -> returns reshaped array into shape of (min,2,2)
## Reshape takes as an input the dimensions comma seperated
arr3DReshaped=arr3D.reshape(-1,2,2)
print(arr3DReshaped)

[[[1 2 3 4 5 6 7 8]]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [6]:
## Accessing elements in one dimesnional numpy array similar to python lists
print(numpyArr[1], listX[1])
## Accessing element sin multi-dimensional numpy arrays can be done in 2 ways
print(arr3DReshaped[0,0], arr3DReshaped[0][0])
## Accessing last element in an array (Think of it as circular array from -len to len-1)
print(numpyArrOfElements[-1])

2 2
[1 2] [1 2]
8


In [7]:
## Array Slicing --> Extract elements based on given indices
print(numpyArrOfElements[1:8:2], numpyArrOfElements[-2:],
      numpyArrOfElements[:-2])

[2 4 6 8] [7 8] [1 2 3 4 5 6]


In [8]:
numpyArrOfElements2 = numpyArrOfElements
numpyArrOfElements[0] =100
print(numpyArrOfElements2)
numpyArrOfElements3 = numpyArrOfElements.copy()
numpyArrOfElements[0]=1
print(numpyArrOfElements, numpyArrOfElements2, numpyArrOfElements3)

[100   2   3   4   5   6   7   8]
[1 2 3 4 5 6 7 8] [1 2 3 4 5 6 7 8] [100   2   3   4   5   6   7   8]


In [9]:
## 3 Function usually used to initiate an array of given size
## Given size of zeros
zerosArray = np.zeros((2,4))
onesArray = np.ones((2,4))
fullArray = np.full((2,3), np.array([1,2,3]))
fullArray

array([[1, 2, 3],
       [1, 2, 3]])

In [10]:
## Concatenate 2 1d Arrays in numpy
firstArray = np.arange(0,3)
secondArray = np.arange(9,12)
print(np.concatenate((firstArray, secondArray)))
## What if: You would like to use concatenation to add a row to a 2D array
array2DConcat = np.arange(0,9).reshape(3,3)
print(np.concatenate((array2DConcat, secondArray.reshape(-1,3))))
# Simpler function for adding rows/columns you have --> vstack/hstack
stackedArray = np.hstack((array2DConcat, secondArray.reshape(3,-1)))
print(stackedArray)
stackedArrayVertical = np.vstack((array2DConcat, secondArray))
print(stackedArrayVertical)

[ 0  1  2  9 10 11]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[ 0  1  2  9]
 [ 3  4  5 10]
 [ 6  7  8 11]]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [11]:
## Return the indices (dimension-wise) where the condition is true
print(np.array(np.where(stackedArrayVertical==7)))
## Sorting numpy array
npUnsorted = np.array([[3,6,1], [2,23,56], [1,45,-1]])
print(npUnsorted, '\n', np.sort(npUnsorted, axis=0), '\n', np.sort(npUnsorted))
## What if: [[-1,1,1], ..]
## Sorting All Elements
## 1. Flatten (array becomes one dimensional array)
## 2. Sort the array
## 3. Reshape to original shape
print(np.sort(npUnsorted.flatten()).reshape(npUnsorted.shape))

[[2]
 [1]]
[[ 3  6  1]
 [ 2 23 56]
 [ 1 45 -1]] 
 [[ 1  6 -1]
 [ 2 23  1]
 [ 3 45 56]] 
 [[ 1  3  6]
 [ 2 23 56]
 [-1  1 45]]
[[-1  1  1]
 [ 2  3  6]
 [23 45 56]]


In [12]:
## Extracting elements based on filter criteria inside where clause
npUnsorted[np.where(npUnsorted<20)]

array([ 3,  6,  1,  2,  1, -1])

In [17]:
## Creating random np array with size given
randomIntArr = np.random.randint(0,10, size=(10,2))
print(randomIntArr)
np.random.rand(2,2) ## NOTE: 0 and 1 are unexpected values (1 in a million chance)

[[7 1]
 [0 1]
 [4 6]
 [5 9]
 [1 6]
 [2 9]
 [6 3]
 [6 5]
 [7 8]
 [6 7]]


array([[0.61088893, 0.88426288],
       [0.79283995, 0.64140056]])

## Pandas

In [18]:
import pandas as pd
print(pd.__version__)

1.3.0


In [25]:
## Note: Notice the index
creatingPdSeries = pd.Series([1,2,3,np.nan])
print(creatingPdSeries, creatingPdSeries.index)
## PD Date Range
## Note: The frequency and periods usage check pd documentation
print(pd.date_range("09/01/2023", "12/22/2023", freq="m"), 
      pd.date_range("09/01/2023","09/12/2023", periods=4))

0    1.0
1    2.0
2    3.0
3    NaN
dtype: float64 RangeIndex(start=0, stop=4, step=1)
DatetimeIndex(['2023-09-30', '2023-10-31', '2023-11-30'], dtype='datetime64[ns]', freq='M') DatetimeIndex(['2023-09-01 00:00:00', '2023-09-04 16:00:00',
               '2023-09-08 08:00:00', '2023-09-12 00:00:00'],
              dtype='datetime64[ns]', freq=None)


In [30]:
numpyArrayOfFP = [["Strawberry", 5, 20],
                  ["Raspberry", 8, 100],
                  ["Banana", 1, 200]]
fpDataframe = pd.DataFrame(numpyArrayOfFP, index=[0,1,2], columns=["Name", "Price", "Quantity"])
display(fpDataframe)
dictionaryFP = {"Names": ["Strawberry", "Raspberry", "Banana"],
                "Price":[5,8,1],
                "Quantity":[20,100,200]}
dataframeFromDict=pd.DataFrame(dictionaryFP)
display(dataframeFromDict)
dataframeFromDict.head(1), fpDataframe.tail(2)

Name  Price  Quantity
0  Strawberry      5        20
1   Raspberry      8       100
2      Banana      1       200

Names  Price  Quantity
0  Strawberry      5        20
1   Raspberry      8       100
2      Banana      1       200

(        Names  Price  Quantity
 0  Strawberry      5        20,
         Name  Price  Quantity
 1  Raspberry      8       100
 2     Banana      1       200)